export const languages = {
  eng: 'English',
  chi_sim: 'Chinese Simplified',
  chi_tra: 'Chinese Traditional',
  jpn: 'Japanese',
  kor: 'Korean',
  rus: 'Russian',
  ara: 'Arabic',
  hin: 'Hindi',
  spa: 'Spanish',
  fra: 'French',
  deu: 'German',
  ita: 'Italian',
  por: 'Portuguese',
  vie: 'Vietnamese',
  tha: 'Thai',
  ben: 'Bengali',
  tur: 'Turkish',
  nld: 'Dutch',
  ukr: 'Ukrainian',
  pol: 'Polish',
  heb: 'Hebrew',
  grc: 'Greek',
  fas: 'Persian',
  swe: 'Swedish',
  dan: 'Danish',
  fin: 'Finnish',
  hun: 'Hungarian',
  ind: 'Indonesian',
  mal: 'Malayalam',
  tam: 'Tamil',
  tel: 'Telugu',
  kan: 'Kannada',
  mar: 'Marathi',
  nep: 'Nepali',
  sin: 'Sinhala',
  lao: 'Lao',
  khm: 'Khmer'
} as const;

export type LanguageCode = keyof typeof languages; 